global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    #metrics_path: /metrics
    static_configs:
      - targets:
        - 127.0.0.1:8000
        - group-bse25-34-capstone-eaas.onrender.com