name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Collect static files
      run: |
          python manage.py collectstatic --no-input

    - name: Run tests
      run: |
        python manage.py test

    - name: Check for lint errors
      run: |
        pip install flake8
        flake8 .
