name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Set up Django environment
      run: |
        python3 manage.py migrate
        python3 manage.py collectstatic --no-input

    - name: Collect static files
      run: |
          python3 manage.py collectstatic --no-input

    - name: Run tests
      run: |
        python3 manage.py test
    
    - name: Fix lint errors
      run: |
        pip3 install autopep8
        autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")

    - name: Check for lint errors
      run: |
        pip3 install --upgrade flake8 pycodestyle
        flake8 .

  deploy-staging:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging on PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          curl -s --user $PA_USERNAME:$PA_API_TOKEN https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/Group_BSE25-34-Capstone/reload/
          
      - name: Reload PythonAnywhere app
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/Group_BSE25-34-Capstone/reload/ \
          -H "Authorization: Token $PA_API_TOKEN"

      
