name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'  # Force use of Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        node-version: '20'  # Force use of Node.js 20

    - name: Install geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        sudo apt-get install -y wget
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
        wget https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        tar -xzf geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Run tests
      run: |
        python manage.py test

    - name: Fix lint errors
      run: |
        pip install autopep8
        autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")

    - name: Check for lint errors
      run: |
        pip install --upgrade flake8 pycodestyle
        flake8 .
