name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Django environment
      run: |
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Run tests
      run: |
        python manage.py test

    - name: Fix lint errors
      run: |
        pip install autopep8
        autopep8 --in-place --aggressive --aggressive $(find . -name "*.py")

    - name: Check for lint errors
      run: |
        pip install --upgrade flake8 pycodestyle
        flake8 .

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem

    - name: Deploy to AWS EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2-key.pem ec2-user@13.53.174.244 << 'EOF'
          cd /home/ec2-user/Group_BSE25-34-Capstone
          git pull origin main
          source django-env/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --no-input
          sudo systemctl restart your_web_service
        EOF


    
          

      
